### ISSUE TITLE
Unneeded warning about docker version on OCP

### ISSUE THREAD

**Issue by NissesSenap** [ibm-apiconnect/v10-postmortem#1]
Hi

Running OCP 4.5 and I see the following warning in the logs:

````shell
+ warning1='WARNING!  Node '
+ warning2=' docker version [1.18.3-11.rhaos4.5.gite5bcc71.el8] less than minimum [17.03].'
+ echo -e 'WARNING!  Node xcoreosd102.example.com docker version [1.18.3-11.rhaos4.5.gite5bcc71.el8] less than minimum [17.03].'
WARNING!  Node xcoreosd102.example.com [1.18.3-11.rhaos4.5.gite5bcc71.el8] less than minimum [17.03].
+ echo -e 'WARNING!  Node xcoreosd102.example.com docker version [1.18.3-11.rhaos4.5.gite5bcc71.el8] less than minimum [17.03].'
````

My docker versions isn't a problem since i don't run docker on my nodes :)
Please add a small if statement check if i run OCP don't test for docker version. Rather check cri-o version.

**Comment by nitekon1** [comment]
@NissesSenap 

Thanks for the heads up!  Will proceed to remove this section of code since in v10 we now check if minimum requires are met before install.

Change added in commit 5e355bb35980d50ef6b576026a6f08595838abdc.
