### ISSUE TITLE
Support multiple subsystems

### ISSUE THREAD

**Issue by nictownsend** [ibm-apiconnect/v10-postmortem#13]
https://github.com/ibm-apiconnect/v10-postmortem/blob/bf8e155b40249ae9c3b894e9f1d9fe183577d9bb/generate_postmortem.sh#L245-L280

does not handle the presence of multiple subsystems (e.g `kubectl get PortalCluster` returns multiple listings)

**Comment by nitekon1** [comment]
Added in commit 90d6f83af3868072c8c4a5d7ca1cb944d16cf093.
