### ISSUE TITLE
generate postmortem throwing an error

### ISSUE THREAD

**Issue by mariaobias** [ibm-apiconnect/v10-postmortem#15]
When using generate postmortem script for ova, it gives this error
root@manager-esbnpe:~# ./generate_postmortem.sh --ova
Generating postmortem, please wait...
./generate_postmortem.sh: line 283: [: -eq: unary operator expected
Auto-detected namespaces [default].
./generate_postmortem.sh: line 298: [: -eq: unary operator expected

ran ./generate_postmortem.sh --debug 2>&1 | tee /tmp/debug.log per documentation, debug.log attached
[debug.log](https://github.com/ibm-apiconnect/v10-postmortem/files/6151598/debug.log)

**Comment by nitekon1** [comment]
Fixed in commit 90d6f83af3868072c8c4a5d7ca1cb944d16cf093.
