### ISSUE TITLE
Include webhookconfigurations and managementbackups in postmortem output

### ISSUE THREAD

**Issue by rosemarm-ie** [ibm-apiconnect/v10-postmortem#17]
Please add the output from the following commands into the postmortem output

kubectl get validatingwebhookconfiguration -n <namespace>
kubectl get mutatingwebhookconfiguration -n <namespace>

And also, please include the following:

kubectl get managementbackup -n <namespace>

Then loop through and get the config for each of the management backups

kubectl get managementbackup <management backup name> -o yaml -n <namespace>

**Comment by NiharDudam** [comment]
@rosemarm-ie - Seems like we already have details about managementbackup as per current postmortem

**Comment by rosemarm-ie** [comment]
They were missing from a few of my tickets, so I didn't think they were included, but yeah, they are, sorry. 
We dont have the webhookconfigurations though.

**Comment by nitekon1** [comment]
Added in commit 2a7b16387cbdb5688ea6748e9bc114eba27bcf7b.
