### ISSUE TITLE
Collect backup config and logs

### ISSUE THREAD

**Issue by subindani** [ibm-apiconnect/v10-postmortem#2]
Please add a module to collect backup configuration and logs. For example:
For portal backup:
kubectl get portalbackup portal-fjd-y7teyr -o yaml

**Comment by nitekon1** [comment]
@subindani 
Will consider for `release-1.2`.  
From review of the following help article:
https://www.ibm.com/support/knowledgecenter/SSMNED_v10/com.ibm.apic.install.doc/tapic_db_backup_portal.html

Have a few questions:
1) Are you requesting the actual backup file(s) pulled?
2) Specifically what logs?
3) If wanting a specific or latest backup pulled, what is the size of these files?  If able to grow upwards to 100MB+ or GBs then not sure be the ideal method.

Also suggest asking for feedback from the Portal team.

**Comment by subindani** [comment]
@nitekon1 As discussed:

Use first command to get the list of backups
```
kubectl get portalbackup -n apicsubin
```

Then, using a loop we can get config and logs of each backup using the second command 
```
kubectl get portalbackup <backup_name>  -o yaml -n apicsubin
```
