### ISSUE TITLE
Add storage-shared to get analytics cluster health

### ISSUE THREAD

**Issue by subindani** [ibm-apiconnect/v10-postmortem#21]
Noticed in an issue the pod name is `analyt-storage-shared-0` for v10 OVA. 

Please add a new condition in the if loop at : 

Change 
https://github.com/ibm-apiconnect/v10-postmortem/blob/7cba4f8b015158e8fb2e25e816d45124e318938d/generate_postmortem.sh#L1068
to
```
if [[ "$pod" == *"storage-data"* || "$pod" == *"storage-basic"* || "$pod" == *"storage-shared"* ]]; then 
```

**Comment by nitekon1** [comment]
Fixed in commit 67133485b86cee3bb45b7b1b6fa96abe3e04a1d2.
