### ISSUE TITLE
postmortem should include v10 CRs for both APIC and DP operators

### ISSUE THREAD

**Issue by aharbis** [ibm-apiconnect/v10-postmortem#29]
There are several custom resources that compose the APIC subsystems, each with their own CRD and CR instance. The postmortem tool should dump these resources to YAML as part of the data collection, so that IBM support and development teams can review their specs and status.

Here's a list of the kinds (in plural form) from a 10.0.2.0 APIC (+DP) package:

- natsclusters
- natsserviceroles
- natsstreamingclusters
- analyticsbackups
- analyticsclusters
- analyticsrestores
- apiconnectclusters
- gatewayclusters
- managementbackups
- managementclusters
- managementdbupgrades
- managementrestores
- managementsecretrotations
- pgclusters
- pgpolicies
- pgreplicas
- pgtasks
- portalbackups
- portalclusters
- portalrestores
- portalsecretrotations
- datapowerservices
- datapowermonitors

Within the postmortem, I would expect to see `kubectl get -o yaml` output from each CR instance, so that we can review customer provided configuration of these CRs, and their status.

**Comment by nitekon1** [comment]
@aharbis 
Added in commit #5d49632a2f8439c156402bf97417c432e0c40fb0.
