### ISSUE TITLE
Add getting secrets to tool output

### ISSUE THREAD

**Issue by mkolinsk** [ibm-apiconnect/v10-postmortem#3]
```kubectl get secrets -n namespace -o yaml > secrets.yaml```

This is extremely helpful in debugging cert issues when clients customize certs.

**Comment by nitekon1** [comment]
@mkolinsk 
In older version of the tool we did collect this data by default.  Later it was removed due to sensitive nature of the data.
Added switch `--collect-secrets` to collect data.

Added in commit 2c2dd4314db25dbc190fee0f8058571753eac403.
