### ISSUE TITLE
Postmortem tool should collect kube-system level details for Open Shift / CP4I

### ISSUE THREAD

**Issue by hmoobed** [ibm-apiconnect/v10-postmortem#32]
Just like a regular k8s environment where we collect kube-system level details, in Open Shift and CP4i we should do the same.  
We have had a number of customer issues where we needed to do root cause analysis and having collected those details would have been really useful.
This is also true for debugging customer cases (Sev 1s etc), where we have to ask them again to collect those details and send it to us, thus causing unnecessary delays

**Comment by hmoobed** [comment]
Here is an example of what was collected for kube-system pods on cp4i on openshift which was pretty much useless:
```
NAME                              READY   STATUS             RESTARTS   AGE   IP            NODE             NOMINATED NODE   READINESS GATES
metrics-server-77778446df-mftg8   0/1     CrashLoopBackOff   9556       20d   12.131.4.51   worker3.tjcocp   <none>           <none>
```

**Comment by nitekon1** [comment]
@hmoobed OCP does not place pods in the `kube-system` namespace.  In OCP, these pods are broken out into multiple `openshift-*` namespaces.  Recommend discussing with OCP SME to see what namespaces may be useful to collect data.

**Comment by louiseohalloran** [comment]
CP4i must gather should be run to collect this data along with apiconnect data - that script has been improved to include everything needed for apiconnect - so this data is laready collected there.

@hmoobed does that sound ok to you and is this therefore ok to close ?

FYI @mkolinsk

**Comment by hmoobed** [comment]
Yes, thanks.
