### ISSUE TITLE
For OCP installation (CP4I or native OCP) we need to collect InstallPlan, Subscription, and ClusterServiceVersion

### ISSUE THREAD

**Issue by mkolinsk** [ibm-apiconnect/v10-postmortem#34]
For installation related issues and to know the status of key resources related to the deployment, we need to collect additional data (get, get -o yaml, and describe) for the following resources in the `openshift-operators` namespace

- InstallPlan (ip)
- Subscription (sub)
- ClusterServiceVersion (csv)

**Comment by nitekon1** [comment]
@mkolinsk 
Added in commit #5d49632a2f8439c156402bf97417c432e0c40fb0.
