### ISSUE TITLE
Update Diagnostic-gateway logic for pulling logs to accomodate CP4I

### ISSUE THREAD

**Issue by jtbarret** [ibm-apiconnect/v10-postmortem#37]
Currently the logic to pull diagnostic gateway logs is:

#grab gateway diagnostic data
            if [[ $DIAG_GATEWAY -eq 1 && $IS_GATEWAY -eq 1 && "$ready" == "1/1" && "$status" == "Running" && "$pod" != *"monitor"* && "$pod" != *"operator"* ]]; then
            
I've recently seen a CP4I customer where their gateway pods have 3 containers (datapower, od-tracing-agent and od-tracing-collector) and the pods.out show 3/3 for these pods, so the logic doesn't match.

**Comment by jtbarret** [comment]
I had the customer run the current script with the ready condition not being checked. It successfully pulled gwd logs, but error report is missing. I think it needs to somehow check the container

                    #pull error report
                    echo -e "Pausing for error report to generate..."
                    sleep $ERROR_REPORT_SLEEP_TIMEOUT

                    #this will give a link that points to the target error report
                    kubectl cp -n $NAMESPACE "${pod}:/opt/ibm/datapower/drouter/temporary/error-report.txt.gz" "${GATEWAY_DIAGNOSTIC_DATA}/error-report.txt.gz"

**Comment by nitekon1** [comment]
@jtbarret 
The issue here in CP4i we now generate a unique password.  So the credentials `admin / admin` no longer work.
Updating code to address this change.

**Comment by nitekon1** [comment]
@jtbarret 
Fixed in commit 5d49632a2f8439c156402bf97417c432e0c40fb0.
