### ISSUE TITLE
Postmortem should collect all management Upgrade CR's on OCP/CP4I env 

### ISSUE THREAD

**Issue by ychetanreddy** [ibm-apiconnect/v10-postmortem#38]
On an upgraded system, we usually generate new upgrade CR's while still keep the old ones around for debugging purposes. 
For ex. `oc get apic` will list all the CR's for ManagementDBUpgrade.
```
NAME                                                                      STATUS     MESSAGE                                                     AGE
managementdbupgrade.management.apiconnect.ibm.com/minimum-mgmt-up-n4m68   Complete   Upgrade is Complete (DB Schema/data are up-to-date)         43m
managementdbupgrade.management.apiconnect.ibm.com/minimum-mgmt-up-n6f6x   Complete   Fresh install is Complete (DB Schema/data are up-to-date)   95m
```

I believe we capture this list in postmortem under `/kubernetes/namespace/apic/clusters/ManagementDBUpgrade.out` but we do not capture the yaml output of all the CR's or even the latest one. 
`/kubernetes/namespace/apic/clusters/ManagementDBUpgrade.out`:
```
NAME                    STATUS     MESSAGE                                                     AGE
minimum-mgmt-up-n4m68   Complete   Upgrade is Complete (DB Schema/data are up-to-date)         12m
minimum-mgmt-up-n6f6x   Complete   Fresh install is Complete (DB Schema/data are up-to-date)   63m
```
These CR's will show the history of the management system upgrades. 
Can we have these CR's included as part of the yaml collection when we take postmortem?

**Comment by nitekon1** [comment]
@ychetanreddy 
Per following section of code:
```
    #grab cluster configuration, equivalent to "apiconnect-up.yml" which now resides in cluster
    CLUSTER_LIST=(apic ManagementCluster ManagementBackup ManagementRestore ManagamentDBUpgrade AnalyticsCluster PortalCluster GatewayCluster)
    for cluster in ${CLUSTER_LIST[@]}; do
        OUTPUT=`kubectl get -n $NAMESPACE $cluster 2>/dev/null`
        if [[ $? -eq 0 && ${#OUTPUT} -gt 0 ]]; then
            echo "${OUTPUT}" > "${K8S_NAMESPACES_CLUSTER_DATA}/${cluster}.out"

            kubectl describe $cluster -n $NAMESPACE &>"${K8S_NAMESPACES_CLUSTER_DESCRIBE_DATA}/${cluster}.out"
            [ $? -eq 0 ] || rm -f "${K8S_NAMESPACES_CLUSTER_DESCRIBE_DATA}/${cluster}.out"

            kubectl get $cluster -n $NAMESPACE -o yaml &>"${K8S_NAMESPACES_CLUSTER_YAML_OUTPUT}/${cluster}.yaml"
            [ $? -eq 0 ] || rm -f "${K8S_NAMESPACES_CLUSTER_YAML_OUTPUT}/${cluster}.yaml"
        fi
    done
```

the YAML output for the cluster is sent to the directory:
```
/kubernetes/namespace/${NAMESPACE}/clusters/yaml
```
In this case, the requested YAML for the requested CR would be in the file `ManagamentDBUpgrade.yaml`.
Do you have an example where this directory is either missing or not present?

**Comment by ychetanreddy** [comment]
@nitekon1 there can be multiple CR's, so we need to capture them all to `/clusters/yaml` directory.

For ex. in this instance 
`/kubernetes/namespace/apic/clusters/ManagementDBUpgrade.out`
there are two CRs
- minimum-mgmt-up-n4m68  
- minimum-mgmt-up-n6f6x
which we want to collect during postmortem

**Comment by nitekon1** [comment]
If I understand correctly, the following command:
```
kubectl get ManagementDBUpgrade -o yaml
```
should also capture these CRs.  Is this assumption incorrect?
