### ISSUE TITLE
CP4I and v10 postmortem

### ISSUE THREAD

**Issue by mkolinsk** [ibm-apiconnect/v10-postmortem#4]
1. Does the tool always autodetect namespaces and collect data on all those namespaces detected? 
2. Based upon answer to 1, can we document the recommended way to run the tool on v10 CP4I.

We no longer have the CP4I flag and the tool now auto-detects namespaces. I recently worked with a client who has 3 namespaces in the same cluster, and he reported that even when he passed `--extra-namespaces=namespace1`, that namespace2 & namespace3 were also collected. 

Let's take the example of 3 APIC deployments (each with their own namespace) within the same cluster:  apicDev, apicStage & apicProd. If the following command is issued, I believe it will not prompt regarding the auto-detected namespaces but still collect data from those namespaces (apicDev, apicStage & apicProd). However, i could be reading the script incorrectly.
```./generate_postmortem.sh  --extra-namespaces=apicTest```

**Comment by nitekon1** [comment]
@mkolinsk 
See responses below:
1) By default, tool will check all namespaces for API Connect cluster operators.
2) Running the tool on CP4i is no different than any other platform now.

The configuration described here is not specific to OCP / CP4i and may also exists in a pure Kubernetes deployment.
Added switch `--specific-namespaces` which will not append detected namespaces to the global list.

Added in commit 2c2dd4314db25dbc190fee0f8058571753eac403.
