### ISSUE TITLE
Update Diagnostic-gateway logic for pulling logs to accomodate CP4I 

### ISSUE THREAD

**Issue by jtbarret** [ibm-apiconnect/v10-postmortem#41]
Continued from issue 37

 I believe the check for "$ready"=="1/1" at line 1055 needs to be updated as CP4I Gateway pods can contain 3 containers (datapower, od-tracing-agent, and od-tracing-collector). 
 
 I have suggested customers update this logic and seen the diagnostic folder started to populate when it didn't before

Relevant code snippet
```
#grab gateway diagnostic data
if [[ $DIAG_GATEWAY -eq 1 && $IS_GATEWAY -eq 1 && "$ready" == "1/1" && "$status" == "Running" && "$pod" != "monitor" && "$pod" != "operator" ]]; then
GATEWAY_DIAGNOSTIC_DATA="${K8S_NAMESPACES_POD_DIAGNOSTIC_DATA}/gateway/${pod}"
```

**Comment by nitekon1** [comment]
Updated algorithm to detect if pod is ready.  Fixed in commit e3126a540de6464bb78cf842b263ac53d5445362.
