### ISSUE TITLE
Update OVA postmortem collection example

### ISSUE THREAD

**Issue by xor76** [ibm-apiconnect/v10-postmortem#5]
Can we replace the example in the README with this one

```
./generate_postmortem.sh 0 --ova --pull-appliance-logs --diagnostic-manager
```

so we are consistent with the mustgather for v10

**Comment by nitekon1** [comment]
@xor76 
The referenced command is specific to pulling logs for the management cluster.  Would not recommend pulling appliance logs nor generating diagnostics in all cases.
