### ISSUE TITLE
Be able to run postmortem with --since=xh or xm flag

### ISSUE THREAD

**Issue by micoletta** [ibm-apiconnect/v10-postmortem#64]
Would be nice if postmortem had option to collect logs just for the last hour vs full logs etc.
similar to kubernetes logs --since=xx option

**Comment by subindani** [comment]
@micoletta Does [log_limit](https://github.com/ibm-apiconnect/v10-postmortem/blob/118473c93d58041be4eb738a8b7a7071d7a743c6/generate_postmortem.sh#L21) help with your requirement ?

**Comment by dfibm** [comment]
Any news on this idea? I was about to post the same idea, also allow specific timestamp input for those scenarios when the customer is aware when the problem initiated.

Thanks.

**Comment by louiseohalloran** [comment]
@micoletta @dfibm  - Not sure I see the benefit of this issue - from perspective of those analysing the logs - I think it is best to see as much as possible. If goal here is how long it takes to run - we have other plans to speed up the running of post mortem.
