### ISSUE TITLE
Using oc instead of kubectl on Line 65 - breaks in non ocp envs

### ISSUE THREAD

**Issue by louiseohalloran** [ibm-apiconnect/v10-postmortem#65]
APIV v10.0.5.1 (OVA)

```
./generate_postmortem.sh 0 --ova --pull-appliance-logs --diagnostic-manager

./generate_postmortem.sh: line 65: oc: command not found

Generating postmortem, please wait...

Auto-detected namespaces [default].

Created [/tmp/apiconnect-logs-srv1-20221104T014656UTC.zip].

Cleaning up. Removing directory [/tmp/postmortem-20221104T014656UTC].
```

--

According to the following, the line65 is `"EDB_CLUSTER_NAME=$(oc get cluster --all-namespaces -o=jsonpath='{.items[0].metadata.name}')".`

https://github.com/ibm-apiconnect/v10-postmortem/blob/master/generate_postmortem.sh

==

```
*"--diagnostic-manager"*)

           DIAG_MANAGER=1

           EDB_CLUSTER_NAME=$(oc get cluster --all-namespaces -o=jsonpath='{.items[0].metadata.name}')   <=== Line 65

           if [[ -z "$EDB_CLUSTER_NAME" ]]; then

               COLLECT_CRUNCHY=1

               SCRIPT_LOCATION="`pwd`/crunchy_gather.py"
```

==

https://jazz609.hursley.ibm.com:9443/jazz/web/projects/Salesforce%20Cases%20for%20API%20Connect#action=com.ibm.team.workitem.viewWorkItem&id=85682

oc needs to be changed to kubectl

**Comment by subindani** [comment]
This should be fixed with https://github.com/ibm-apiconnect/v10-postmortem/pull/66

**Comment by geraintwjones** [comment]
Does `kubectl` work in OCP environments? Would it not be better to use `oc` if running this script on OCP?
